export const CLIENT_ACTIONS = {
  SET_USER: 'SET_USER',
  SET_ROLES: 'SET_ROLES',
  SET_THEME: 'SET_THEME',
  SET_LANGUAGE: 'SET_LANGUAGE',
  SET_ADDRESS_LIST: 'SET_ADDRESS_LIST',
  SET_CREDIT_CARDS: 'SET_CREDIT_CARDS'
};

export const PRODUCT_ACTIONS = {
  SET_CATEGORIES: 'SET_CATEGORIES',
  SET_PRODUCT_LIST: 'SET_PRODUCT_LIST',
  SET_TOTAL: 'SET_TOTAL',
  SET_FETCH_STATE: 'SET_FETCH_STATE',
  SET_LIMIT: 'SET_LIMIT',
  SET_OFFSET: 'SET_OFFSET',
  SET_FILTER: 'SET_FILTER'
};

export const SHOPPING_CART_ACTIONS = {
  SET_CART: 'SET_CART',
  SET_PAYMENT: 'SET_PAYMENT',
  SET_ADDRESS: 'SET_ADDRESS'
};
